[package]
name = "rusty_marta"
version = "0.1.0"
authors = ["trentgillin <trentgillin@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
serde = "1.0.106"
serde_derive = "1.0.106"
structopt = "0.3.14"